### ISSUE TITLE
Memory Error while reading nrrd in Windows

### ISSUE THREAD

**Issue by V-vp** [mhe/pynrrd#107]
`n,_ = nrrd.read("1.nrrd")`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Apex\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nrrd\reader.py", line 508, in read
    data = read_data(header, fh, filename, index_order)
  File "C:\Users\Apex\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nrrd\reader.py", line 439, in read_data
    decompressed_data += decompobj.decompress(compressed_data[start_index:end_index])
MemoryError

**Comment by addisonElliott** [comment]
Hello, thanks for the issue. At first glance, this seems to be because you don't have enough RAM to load the entire NRRD into memory.

Does that make sense?

**Comment by V-vp** [comment]
Its not ram issue.
Its able to load nrrd with 100 mb size but failing in this perticular nrrd which is only 1 mb.

**Comment by addisonElliott** [comment]
Oh okay, well then that definitely sounds like a problem. Can you attach the NRRD file and I'll take a look at it later?

In case you need a fix immediately, this should be easy to diagnose, here are the steps I'm going to take:
- Set breakpoint at line 439 in reader.py and see size of compress_data. Check the start_index and end_index to make sure they are sensible. 
- From there, that should be indicative of what the problem is. I would also check this NRRD in 3D Slicer and make sure that it can load it. The NRRD file itself may be corrupt.

**Comment by V-vp** [comment]
I am closing this issue since we are facing this issue in one particular windows machine.
