### ISSUE TITLE
Is the conda forge version up to date?

### ISSUE THREAD

**Issue by AngCamp** [mhe/pynrrd#146]
I may be naive with conda but the last upload in conda was mroe than 2 and a half years ago as of the time of raising this issue.  Seven months and two years to be precise, https://anaconda.org/conda-forge/pynrrd.   If I use conda-forge will this give me the current version or should I use pip?  If I do use pip how will this affect the ability for me to share the conda environment?

**Comment by addisonElliott** [comment]
You're correct that v0.4.2 is not up-to-date. It's 2 releases behind: https://github.com/mhe/pynrrd/releases

Note that this library doesn't get updated very often.

Regardless, I don't use Anaconda or conda-forge enough to comment on how to use it. However, I would recommend using pip instead of conda-forge if possible.

**Comment by AngCamp** [comment]
I did in the end use pip which I think can handle it, my concern is about reproducibility.  I'm a researcher in bioinformatics so if this ends up being part of a pipeline I'm building or an analysis I want to be able to share the exact environment I ran everything in.  If I share the .yml of my environment will it be usable?  Because I think the .yml will automatically pull from the conda-forge version.  

May I ask why the conda forge is not being updated?  Do you not maintain it?

**Comment by addisonElliott** [comment]
> If I share the .yml of my environment will it be usable? Because I think the .yml will automatically pull from the conda-forge version.

Not sure. Can you test that and see? If it pulls via pip, or if there's a way to specify to retrieve from pip, then I think this issue is moot.

> May I ask why the conda forge is not being updated? Do you not maintain it?

I don't know who/how the conda-forge version is on there. I began maintaining this library starting on v0.2.5, which is before the conda-forge version. Nothing is done on our end to maintain that.

I'm not opposed to maintaining that version. Preferably, this would automatically happen when a GitHub release is made. Preferably via a GitHub action. PRs are welcome.
